spring:
  redis:
    host: 192.168.234.128 # home
    # host: 192.168.1.79  # company
    port: 6379
    database: 0


knife4j:
  application-title: agileway examples
  base-package: com.jn.agileway.redis.examples.controller

agileway:
  httpClient:
    enabled: true
  redis:
    enabled: true
    global-template:
      enabled: true
      key:
        prefix: agileway_redis_test
  rest:
    global-response-body:
      base-packages: com.jn.agileway.redis.examples.controller
