spring:
  redis:
    #host: 192.168.234.128 # home
    host: 192.168.1.79  # company
    port: 6379
    database: 0


knife4j:
  application-title: agileway examples
  base-package: com.jn.agileway.redis.examples.controller

agileway:
  web:
    access-log:
      level: BODY
    waf:
      xss:
        enabled: true
        predicates:
          - paths=/** /swagger-ui.html
      sql-injection:
        enabled: true
        predicates:
          - paths=/**
          - methods=GET,POST
    set-header:
      rules:
        - predicates:
            - path=/**
          header: X-ContentType-Options
          value: nosniff
        - predicates:
            - path=/**
          header: X-Frame-Options
          value: sameorigin
  httpclient:
    enabled: true
  redis:
    enabled: true
    global-template:
      enabled: true
      key:
        prefix: agileway_redis_test
  rest:
    global-response-body:
      base-packages: com.jn.agileway.redis.examples.controller
      ignoredFields: [success, statusCode, requestHeaders, responseHeaders, url, method, timestamp]
logging:
  level:
    com:
      jn:
        agileway:
          web:
            filter:
              accesslog: debug